### ISSUE TITLE
Error running app

### ISSUE THREAD

**Issue by yuhsuanlii** [kuanrongchan/STAGES#10]
Hello,
when I used this APP to adjust the parameters today, halfway through the adjustment, it directly shut down the entire page, showing that it could not run.

**Comment by kuanrongchan** [comment]
Thank you for informing us. We have restarted the app and tested that it runs. Let us know if you encounter any other problems. Happy to help!

**Comment by yuhsuanlii** [comment]
Thanks for your help! It's working fine now 👍🏻
