### ISSUE TITLE
STAGEs error

### ISSUE THREAD

**Issue by mmshekibi** [kuanrongchan/STAGES#13]
I was hoping to use the STAGEs platform (using the link provided in the journal article) but it sent me to a screen saying there was an error running the app. I tried to open the link on different browsers and it still didn't work. I also asked someone else to try the link, in case it was an issue with my device, but they also encountered an error screen.

**Comment by kuanrongchan** [comment]
Sincere apologies. We have restarted the app which should work now. We are recently receiving high traffic and having people uploading very big datasets which tends to crash the app. We are currently monitoring and ensuring that the app continues to work. In the event where you think that you will be using the app more frequently, you may consider running STAGEs locally on your computer. Thank you.
