### ISSUE TITLE
File attached for the issue to check. 

### ISSUE THREAD

**Issue by prajishiyer** [kuanrongchan/STAGES#2]
[NSG vs primary .xlsx](https://github.com/kuanrongchan/STAGES/files/11392368/NSG.vs.primary.xlsx)

**Comment by kohcl17** [comment]
Hi there, the pvalue column had extra whitespace at the end. I've attached a fix to your file. :)

[NSG_vs_primary.xlsx](https://github.com/kuanrongchan/STAGES/files/11392457/NSG_vs_primary.xlsx)
