### ISSUE TITLE
At least 2 genes must be entered or more than 1 comparison must be made!

### ISSUE THREAD

**Issue by esiefker** [kuanrongchan/STAGES#21]
Clustergram always gives me this error.  I don't see anywhere to specify a comparison.  

I have performed DEG analysis, and provided the DEG lists in the "Select DEGs to use in clustergram" box. 
It lists every gene in those lists under "missing_genes".  What are they missing from?

What else do I need to do to make this run?

**Comment by kohcl17** [comment]
Hi,
Thanks for pointing out the bug! This issue has now been resolved.
