### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by NgoziA** [kuanrongchan/STAGES#24]
I have been trying to upload but I keep running in this issue
I don't know what it means
<img width="688" alt="Screenshot 2024-06-14 at 7 41 43 AM" src="https://github.com/kuanrongchan/STAGES/assets/101666089/760bbb7d-0a7a-46e7-8aa2-d7ac81aac9ba">

**Comment by NgoziA** [comment]
This shows up on every feature

**Comment by kohcl17** [comment]
> This shows up on every feature

Hi,

Thanks for reporting this bug. This was caused by a version dependency error when importing one of the packages.
It has now been resolved and you may try using the app again.

Cheers,
Clara
