### ISSUE TITLE
Issues Uploading Count Data

### ISSUE THREAD

**Issue by treodeo** [kuanrongchan/STAGES#3]
Hello,

I'm having trouble uploading my counts table. No errors pop up but viewing the gene expression data shows no table. When I go to Pre-Processing this error shows up:
![image](https://user-images.githubusercontent.com/6070112/236098527-0f196ec4-7f34-4144-9bfd-9ee26811e709.png)
```
File "/home/appuser/venv/lib/python3.7/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
File "/app/stages/pages/02_Pre-processing.py", line 89, in <module>
    expr_obj = exprdict[list(exprdict.keys())[0]].T.sort_index(axis=0, ascending=True)
```
These are the count and metadata files I'm using. Maybe I have the wrong format?
[LT37_ExpDesign_Stages.csv](https://github.com/kuanrongchan/STAGES/files/11392508/LT37_ExpDesign_Stages.csv)
[FeatureCounts.GeneSymbols.csv](https://github.com/kuanrongchan/STAGES/files/11392527/FeatureCounts.GeneSymbols.csv)

Best,
LT

**Comment by kohcl17** [comment]
Hi LT,

I believe the issue would be related to the file name for your feature counts. The program parses the full stops for file names, so this may have resulted in you being unable to upload the count data. 

A suitable name would be to replace the file name with "FeatureCounts_GeneSymbols.csv" (as attached below).

[FeatureCounts_GeneSymbols.csv](https://github.com/kuanrongchan/STAGES/files/11392553/FeatureCounts_GeneSymbols.csv)

**Comment by treodeo** [comment]
I'm going to keep using this thread to troubleshoot my data if that's okay. The file upload worked now but now I got stock on the pre-processing.

These are my settings:
![image](https://user-images.githubusercontent.com/6070112/236101572-6978718b-40ff-4ca3-a05c-5a3ffcad6433.png)
 
The pre-processing graves render but I get the following error for the after pre-processing.
`File "/home/appuser/venv/lib/python3.7/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
File "/app/stages/pages/02_Pre-processing.py", line 142, in <module>
    violin2, vaxes2 = counts_pp.multiviolin(adata, split_long_violins=split_long_violins)
File "/app/stages/helper_functions/preprocessing.py", line 80, in multiviolin
    color = "#00ABFD")
File "/home/appuser/venv/lib/python3.7/site-packages/decoupler/plotting.py", line 248, in plot_violins
    sns.violinplot(x=x, y=y, ax=ax, color=color)
File "/home/appuser/venv/lib/python3.7/site-packages/seaborn/categorical.py", line 2308, in violinplot
    color, palette, saturation)
File "/home/appuser/venv/lib/python3.7/site-packages/seaborn/categorical.py", line 902, in __init__
    self.establish_colors(color, palette, saturation)
File "/home/appuser/venv/lib/python3.7/site-packages/seaborn/categorical.py", line 707, in establish_colors
    lum = min(light_vals) * .6`

**Comment by kohcl17** [comment]
Hi there,

I believe your threshold for the violin plot was too stringent. As such, this may have resulted in the program being unable to plot anything. You could try removing these limits as this stage and setting it to 0.

**Comment by treodeo** [comment]
Hi Kuan Rong Chan,

Even with a 0 filter, there seems to be only one gene that makes it through the filtering process.
![image](https://user-images.githubusercontent.com/6070112/236105272-1c907e01-f988-4210-8ad5-a059748c94a5.png)
 
![image](https://user-images.githubusercontent.com/6070112/236105283-658e27b5-30e4-49d3-8c52-87868d45a1d7.png)

**Comment by kohcl17** [comment]
Hi LT,

Upon reviewing your dataset, it seems that only 1 gene has non-zero values across all samples. As such, if you'd like to skip the preprocessing step, perhaps you could do a log2-transformation on the data and upload the file as a log2-normalised count file. That way, all of your genes will still be considered in your analysis.
