### ISSUE TITLE
Unable to access the streamlit server

### ISSUE THREAD

**Issue by SihamBoum** [kuanrongchan/STAGES#6]
I was able to use the website for a while but then the access was suspended. I get the following message: 
Error running app. If this keeps happening, please [contact support](https://github.com/kuanrongchan/stages/issues/new).

**Comment by kuanrongchan** [comment]
Thank you for trying out STAGEs. We are experiencing a high volume of traffic and some users are running resource intensive components such as GSEA, causing the webtool to exceed the resource limits. We will strive to reboot the app at least twice a day to minimise the risk of such events. We seek your understanding and apologise for any inconvenience caused.
