### ISSUE TITLE
Link does not work

### ISSUE THREAD

**Issue by ErnieBtheDoctor** [kuanrongchan/STAGES#7]
Good morning,
when I click the link I immediately get an error running app. It does not depend on the browser or vpn.
Thanks!
Anna

**Comment by kuanrongchan** [comment]
Many thanks for highlighting this. The main website is experiencing high traffic and may have exceeded the resources limit. While we are requesting for more resources, you may visit: https://kohcl17-stages-mirror-stages-zvg7qu.streamlit.app/ . We sincerely apologise for the inconvenience caused
