### ISSUE TITLE
Over resource limits on Streamlit Cloud

### ISSUE THREAD

**Issue by amitpande74** [kuanrongchan/STAGES#8]
Hey there :wave: Just wanted to let you know that [your app on Streamlit Cloud deployed from this repo](https://kuanrongchan-stages-stages-vpgh46.streamlit.app/kuanrongchan/stages/main/stages.py) has gone over its resource limits. Access to the app is temporarily limited. Visit the app to see more details and possible solutions.

**Comment by kuanrongchan** [comment]
Many thanks for highlighting this. The main website is experiencing high traffic and thus exceeded the resources limit. While we are requesting for more resources, you may visit our mirror site: https://kohcl17-stages-mirror-stages-zvg7qu.streamlit.app/. We sincerely apologise for the inconvenience caused
